# Generated by Django 3.2.16 on 2022-11-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='dsad', upload_to='pics'),
            preserve_default=False,
        ),
    ]
